// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.




#include "WheelFeed.h"
#include "../RobotMap.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

WheelFeed::WheelFeed() : Subsystem("WheelFeed") {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	rightWheel = RobotMap::wheelFeedRightWheel;
	leftWheel = RobotMap::wheelFeedLeftWheel;
	windowMotor = RobotMap::wheelFeedWindowMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
}
    
void WheelFeed::InitDefaultCommand() {
	// Set the default command for a subsystem here.
	//SetDefaultCommand(new MySpecialCommand());
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
}


// Put methods for controlling this subsystem
// here. Call these from Commands.

void WheelFeed::OpenFeeder() {
	windowMotor->Set(Relay::kReverse);
}

void WheelFeed::CloseFeeder(){
	windowMotor->Set(Relay::kForward);
}

void WheelFeed::StopFeeder() {
	windowMotor->Set(Relay::kOff);
}

void WheelFeed::PullIn() {
	rightWheel->Set(1);
	leftWheel->Set(1);
}

void WheelFeed::PushOut() {
	rightWheel->Set(-1);
	leftWheel->Set(1);
}

void WheelFeed::StopWheels() {
	rightWheel->Set(0);
	leftWheel->Set(0);
}
